/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.clase2;

import com.google.gson.Gson;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IllegalAccessException {
        List<Person> persons = Arrays.asList(new Man(), new Woman());

        Man m = new Man();
        m.imprimirAtributos();

    }

    void generarXml(String xml) {

    }

    void generarXml(Map xml) {

    }
}
